apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: summary-webhook
  namespace: '1049460234657'
  selfLink: >-
    /apis/serving.knative.dev/v1/namespaces/1049460234657/services/summary-webhook
  uid: f87b77a2-cfe8-4ca3-94f6-cdf2c2147f04
  resourceVersion: AAYvsR8exvM
  generation: 2
  creationTimestamp: '2025-03-06T13:43:29.004973Z'
  labels:
    goog-managed-by: cloudfunctions
    goog-cloudfunctions-runtime: python312
    goog-drz-cloudfunctions-id: summary-webhook
    goog-drz-cloudfunctions-location: europe-central2
    cloud.googleapis.com/location: europe-central2
  annotations:
    serving.knative.dev/creator: service-1049460234657@gcf-admin-robot.iam.gserviceaccount.com
    serving.knative.dev/lastModifier: ptasia6concept@gmail.com
    run.googleapis.com/custom-audiences: >-
      ["https://europe-central2-gen-lang-client-0612957264.cloudfunctions.net/summary-webhook"]
    run.googleapis.com/client-name: cloud-console
    run.googleapis.com/build-source-location: >-
      gs://run-sources-gen-lang-client-0612957264-europe-central2/services/summary-webhook/1741287542.136000.zip#1741287542609890
    run.googleapis.com/build-function-target: on_cloud_event
    run.googleapis.com/build-service-account: >-
      projects/gen-lang-client-0612957264/serviceAccounts/1049460234657-compute@developer.gserviceaccount.com
    run.googleapis.com/build-enable-automatic-updates: 'true'
    run.googleapis.com/build-base-image: >-
      europe-central2-docker.pkg.dev/serverless-runtimes/google-22-full/runtimes/python312
    run.googleapis.com/build-image-uri: >-
      europe-central2-docker.pkg.dev/gen-lang-client-0612957264/summary-artifact-repo/summary-webhook
    run.googleapis.com/build-name: >-
      projects/1049460234657/locations/europe-central2/builds/d96c0cbc-1cd1-47fb-a47b-16ce98e4e051
    cloudfunctions.googleapis.com/function-id: summary-webhook
    run.googleapis.com/operation-id: f9aa1b9a-6229-456a-914b-6de450f3182a
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/urls: >-
      ["https://summary-webhook-1049460234657.europe-central2.run.app","https://europe-central2-gen-lang-client-0612957264.cloudfunctions.net/summary-webhook","https://summary-webhook-hvyzropd5a-lm.a.run.app"]
spec:
  template:
    metadata:
      labels:
        run.googleapis.com/startupProbeType: Default
      annotations:
        run.googleapis.com/client-name: cloud-console
        cloudfunctions.googleapis.com/trigger-type: HTTP_TRIGGER
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/startup-cpu-boost: 'true'
        run.googleapis.com/base-images: >-
          {"worker":"europe-central2-docker.pkg.dev/serverless-runtimes/google-22-full/runtimes/python312"}
    spec:
      containerConcurrency: 1
      timeoutSeconds: 60
      serviceAccountName: summary-webhook-sa@gen-lang-client-0612957264.iam.gserviceaccount.com
      containers:
        - name: worker
          image: >-
            europe-central2-docker.pkg.dev/gen-lang-client-0612957264/summary-artifact-repo/summary-webhook@sha256:9c5b4a591cfa5565ac58b0be23440587c6f2b7bcccc226d5e3b3524bc80030be
          ports:
            - name: http1
              containerPort: 8080
          env:
            - name: BQ_DATASET
              value: summary_dataset
            - name: BQ_TABLE
              value: summaries
            - name: DOCAI_LOCATION
              value: us
            - name: DOCAI_PROCESSOR
              value: >-
                projects/gen-lang-client-0612957264/locations/us/processors/4dd65984d08ab626
            - name: LOG_EXECUTION_ID
              value: 'true'
            - name: OUTPUT_BUCKET
              value: summary-main-gen-lang-client-0612957264
          resources:
            limits:
              cpu: '0.5833'
              memory: 1G
          startupProbe:
            timeoutSeconds: 240
            periodSeconds: 240
            failureThreshold: 1
            tcpSocket:
              port: 8080
      runtimeClassName: run.googleapis.com/linux-base-image-update
  traffic:
    - percent: 100
      latestRevision: true
